### PR TITLE
Proposal: Fix line endings

### PR DESCRIPTION
**Pull request by eric**
I found I was getting strange things on macOS when I was trying to look at diffs of changes I made and it appears there's something funny going on with the line endings of files.

I found instructions at https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings and followed them:

1. Creating and committing a new `.gitattributes`
2. Running `git add --renormalize .` and committing that

I did not make any other changes.

### CODE REVIEW

**Comment by erikkaashoek** [comment]
Too many changes for me

**Comment by eric** [comment]
It's definitely a lot of changes, but doing this once will help all of us dealing with conflicting line endings.

If you reconsider I'll have to run this one more time to prevent conflicts.

**Comment by erikkaashoek** [comment]
I will consider but we have to ensure this change is not changing anything except the line endings to ensure clear change steps.

**Comment by eric** [comment]
You can confirm it with this setting in GitHub:

Comskip 2020-03-03 10-49-16

In the future, if other people have outstanding pull requests, they can use this command to make merging easier:

```
$ git merge master -s recursive -X renormalize
```

or set this in their config for the repo:

```
$ git config merge.renormalize true
```

**Pull request merged**
