### PR TITLE
Support for building Comskip using a win32 cross compiler in Ubuntu

### PR DESCRIPTION
**Pull request by rboy1**
Scripts and files for building using mingw-w64 win32 version of Comskip with Ubuntu

### CODE REVIEW

**Comment by tmm1** [comment]
There's a lot of code in here. If you are the author of all these scripts and patches and are going to maintain them, then I think it's better if you put it in another repo under your account.

**Comment by rboy1** [comment]
The mingw, ffmpeg build scripts and the patches folder are taken from here:
https://github.com/rdp/ffmpeg-windows-build-helpers

They are pretty upto date and I've set the command line parameter to not pull the latest github updates so users can rebuild comkip without running into build issues with ffmpeg updates. So once comskip is built a rebuild should be very very fast and stable. I didn't want to download these on the fly because of the same issues, one you have a working solid script, keep it.

The custom script I've put together is the comskip cross compile script which build ffmpeg using the script above, argtable2 and then comskip.

I'll be happy to maintain but I'll leave it to you and @erikkaashoek  to decide if you want to merge it with the master.

**Comment by ZackaryH8** [comment]
Any reason this would happen?
image

**Comment by rboy1** [comment]
@ZackaryH8 were you able to figure it out?

**Pull request closed without merging**
