### PR TITLE
Enable gcc native optimization detection

### PR DESCRIPTION
**Pull request by gdevenyi**
Adds gcc automatic automatic optimization for the hardware gcc is running on.

### CODE REVIEW

**Comment by erikkaashoek** [comment]
This setting breaks the automated travis build check

**Comment by gdevenyi** [comment]
Will take a look at the travis info

**Comment by gdevenyi** [comment]
Hrm, looks like the travis system builds on one type of CPU and then runs on another. So the optimizations don't work.

What about "-mtune=generic" instead? https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html

That will set the hardware optimizations for the most common cpus available and shouldn't case breakage.

**Comment by tmm1** [comment]
This broke cross-compiling to arm, where `-mtune=generic` is not a valid option.

**Comment by erikkaashoek** [comment]
Is there anything I need to do?

2016-04-11 22:49 GMT+02:00 Aman Gupta <notifications@github.com>:

**Pull request merged**
