### PR TITLE
Appveyor support

### PR DESCRIPTION
**Pull request by tmm1**
WIP, adding windows builds

### CODE REVIEW

**Comment by erikkaashoek** [comment]
Should I already merge this or should I wait till its working?

2016-03-07 22:41 GMT+01:00 Aman Gupta <notifications@github.com>:

**Comment by tmm1** [comment]
Please wait, still work in progress

**Comment by erikkaashoek** [comment]
My windows build environment has collapsed with the new ffmpeg version.
Should I be ok when trying to update according to the README instructions?

**Comment by tmm1** [comment]
cc @fflewddur

**Comment by tmm1** [comment]
This is working now. It will build a 64-bit comskip.exe on windows and test it against the same sample file as the travis CI linux build.

**Comment by tmm1** [comment]
Example build: https://ci.appveyor.com/project/erikkaashoek/comskip/build/1.0.71

The generated comskip.exe is also available as an artifact which can be downloaded for testing or use: https://ci.appveyor.com/project/erikkaashoek/comskip/build/1.0.71/artifacts

**Pull request merged**
