### PR TITLE
Improve accuracy of pts cutpoints

### PR DESCRIPTION
**Pull request by tmm1**
This fixes an issue where edl/vdr/ffsplit cutpoints are not correctly synchronized.

For example, here are the black frames detected at a cutpoint with a sample video:

```
-----------------------------
167      33402  1159.875            16       0       4            b          0       0
168      33403  1159.909            16       0       4            b          0       0
169      33404  1159.942            16       0       4        v   b          0       0
170      33405  1159.975            16       0       4        v   b          0       0
171      33406  1160.009            17     372       4        v   b          0       0
172      33407  1160.042            21    1923       4        v           3702       0
173      33408  1160.076            24    4348       4        v           7140      26
174      33409  1160.109            28    7054       4        v           7784      50
175      33410  1160.142            31    9036       4        v          11825      76
176      33411  1160.176            35   11389       4        v          15876      99
177      33412  1160.209            38   13284       4        v          20442     119
178      33413  1160.242            42   15722       4        v          23706     146
179      33414  1160.276            45   17539       4        v          26735     166
180      33415  1160.309            49   19892       4        v          27411     187
181      33416  1160.343            50   20284       4        v          28032     185
-----------------------------
```

Before this change, the generated ffsplit file is:

```
-c copy -ss 24.625 -t 554.821 segment001.ts
-c copy -ss 765.214 -t 259.426 segment002.ts
-c copy -ss 1159.942 -t 443.276 segment003.ts
```

But cutting at 1159.942 would include half a second from the end of the commercial along with the beginning of the show segment.

After this pull request, the generated ffsplit file is as follows:

```
-c copy -ss 24.958 -t 554.054 segment001.ts
-c copy -ss 765.248 -t 258.992 segment002.ts
-c copy -ss 1160.176 -t 442.642 segment003.ts
```

Using these updated cutpoints the resulting segments start on black frames and include no commercial content.

### CODE REVIEW

**Comment by tmm1** [comment]
I used #15 to check which of these black frames were I-frames:

```
-----------------------------
167      33402  1159.875            16       0       4            b          0       0  B
168      33403  1159.909            16       0       4            b          0       0  I
169      33404  1159.942            16       0       4        v   b          0       0  B
170      33405  1159.975            16       0       4        v   b          0       0  B
171      33406  1160.009            17     372       4        v   b          0       0  P
172      33407  1160.042            21    1923       4        v           3702       0  B
173      33408  1160.076            24    4348       4        v           7140      26  B
174      33409  1160.109            28    7054       4        v           7784      50  P
175      33410  1160.142            31    9036       4        v          11825      76  B
176      33411  1160.176            35   11389       4        v          15876      99  P
177      33412  1160.209            38   13284       4        v          20442     119  B
178      33413  1160.242            42   15722       4        v          23706     146  P
179      33414  1160.276            45   17539       4        v          26735     166  B
180      33415  1160.309            49   19892       4        v          27411     187  P
181      33416  1160.343            50   20284       4        v          28032     185  B
-----------------------------
```

It points to the black frame chosen as the cutpoint on master. This seems to suggest that the change in this PR doesn't fix the underlying sync issue, but instead is getting lucky in finding a better cutpoint.

According to this output, frame 33403 at 1159.909 is an I-frame that is completely black (brightness 16). But when I use ffmpeg to extract this frame using the pts, it is clearly not a black frame:

```
$ ffmpeg -ss 1159.909 -i recording.ts -vframes 1 pts.png
```

pts

If instead, I tell ffmpeg to fetch that frame using its number, it comes back black:

```
$ ffmpeg -i recording.ts -vf "select=gte(n\,33403)" -vframes 1 framenum.png
```

framenum

To make sure, I also tried pts but with `-ss` as an input option to match the `-vf` usage:

```
$ ffmpeg -i recording.ts -ss 1159.909 -vframes 1 ptsoutput.png
```

In this case, the frame also comes back black!

So this seems to suggest that ffmpeg is not seeking correctly during "fast-seek" when you pass `-ss` as an input option. However in the ffsplit case, we are already using `-ss` as an output option. But I think ffmpeg still does a fast-seek optimization since it's a stream copy. I tried disabling this behavior with `-noaccurate_seek` and `-accurate_seek` but those flags make no difference.

I'll try to investigate what looks like a seek bug on the ffmpeg side, but it seems that the comskip side is correct and the change in this PR is not required.

**Comment by tmm1** [comment]
> ```
> $ ffmpeg -i recording.ts -ss 1159.909 -vframes 1 ptsoutput.png
> ```
> In this case, the frame also comes back black!

I tried with another output format (to avoid stream-copy side effects), but it isn't actually black when I generate a mpeg1 video stream:

```
$ ffmpeg -i recording.ts -ss 1159.909 -t 10 out.mpg
```

I tried again with the png output, and grabbed 20 frames this time to make sure they weren't all black. The first few are black and then content starts fading in, so the pts seek is definitely correct when converting to png.

```
$ ffmpeg -i recording.ts -ss 1159.909 -vframes 20 out%d.png
```

I noticed that in the png case we're only processing video, so I retried the mpg command with the audio codec disabled (`-an`):

```
$ ffmpeg -i recording.ts -an -ss 1159.909 -t 10 out.mpg
```

And this time it starts correctly at the black frame!!

So it seems that pts behavior changes when processing only video vs processing both audio and video. Maybe this is because the audio stream and video stream have different starting points..

**Comment by tmm1** [comment]
I tried to do a stream copy (ts -> ts) with video only, and it seems in that case even 1159.909 is too late. I had to go back to 1159.700 to get the black frame:

```
$ ffmpeg -i recording.ts -an -c copy -ss 1159.700 -t 10 out.ts
```

I suspect this is all because the audio and video streams start at different pts, so I will try to figure out how ffmpeg constructs in timeline and handles seek in that case.

**Comment by tmm1** [comment]
After reading through the ffmpeg seek code, I discovered `ffmpeg -seek_timestamp 1` which makes the ffsplit pts cutpoints from master work as expected. This makes the hack in this PR unnecessary, so I'm closing it.

**Comment by tmm1** [comment]
Although `output_ffsplit` cuts are working now, `-seek_timestamp` can only be used when seeking which means `output_ffmeta` files used to tag commercials without removing them will still be off.

The flag toggles the following seek code, which might provide some clue about what is missing from comskip's timeline code: https://github.com/FFmpeg/FFmpeg/blob/db91e0edb63afc682ae709f73e3732a4c832944d/ffmpeg_opt.c#L947-L949

**Comment by tmm1** [comment]
This is still not working consistently, even with `-seek_timestamp`.

**Comment by erikkaashoek** [comment]
ffmpeg, when given a timestamp, seeks in two way depending on the input file. 
1:time based seeking using the pts, 
2:byte base seeking using a calculated byte offset in the input file based on a fraction of the duration.
The second code is not correct as it does not check if the pts found is indeed on the spot,
Comskip contains code to detect if the seekbybyte is used and the switches to a binary search algoritm to fineseek the correct pts.
There are recordings in my test suit that even fail that.

**Comment by tmm1** [comment]
I think ffmpeg uses pts-seek on mpeg2ts files but I can double check. I
thought byte-seek was only for corrupted files.

**Comment by erikkaashoek** [comment]
ts files with a corrupt timeline also use byte-seek

**Pull request closed without merging**
