### PR TITLE
GHI 135: Corrected build error emitted by AppYeyor

### PR DESCRIPTION
**Pull request by AhiyaHiya**
Updated URL for ffmpeg to available download host.

### CODE REVIEW

**Comment by AhiyaHiya** [comment]
Build still having issue with corrected URL: closing PR.

**Comment by tmm1** [comment]
Looks like include path issue, maybe you can add -I

**Comment by AhiyaHiya** [comment]
I'm not 100% sure about that. I'm looking at the gcc arguments and the `include` path was added @tmm1 

I can see `-Iffmpeg-N-103507-g70f06dd63c-win64-gpl-shared/include` in:

```
gcc -DPACKAGE_NAME=\"Comskip\" -DPACKAGE_TARNAME=\"comskip\" -DPACKAGE_VERSION=\"0.82.010\" -DPACKAGE_STRING=\"Comskip\ 0.82.010\" -DPACKAGE_BUGREPORT=\"https://github.com/erikkaashoek/Comskip/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"comskip\" -DVERSION=\"0.82.010\" -DHAVE_LIBM=1 -DHAVE_LIBPTHREAD=1 -I.  -Wall -Iargtable2-13/src -Iffmpeg-N-103507-g70f06dd63c-win64-gpl-shared/include -DPROCESS_CC -DDONATOR  -g -O2  -MT comskip-comskip.o -MD -MP -MF .deps/comskip-comskip.Tpo -c -o comskip-comskip.o `test -f 'comskip.c' || echo './'`comskip.c
comskip.c:21:10: fatal error: libavformat/avformat.h: No such file or directory
   21 | #include <libavformat/avformat.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:555: comskip-comskip.o] Error 1
```

**Comment by tmm1** [comment]
I think it should be -lgpl not -gpl

**Pull request closed without merging**
